### PR TITLE
Update ClustalOmega/ClustalW config.guess to latest

### LINKED ISSUE #23: Build failaure on Linux aarch64/arm64
We are going to support Bioconductor on linux aarch64 https://stat.ethz.ch/pipermail/bioc-devel/2023-January/019398.html

We hit a issue on msa:

```
configure: error: cannot guess build type; you must specify one
using C++ compiler: ‘g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
make[2]: Entering directory '/home/biocbuild/bbs-3.17-bioc/meat/msa/src/ClustalW/src'
g++ -std=gnu++14  -I"/home/biocbuild/bbs-3.17-bioc/R/include" -DNDEBUG  -I'/home/biocbuild/bbs-3.17-bioc/R/library/Rcpp/include' -I/usr/local/include   -DHAVE_CONFIG_H -I.  -Wno-deprecated -Wno-unused-result -fPIC  -g -O2  -Wall  -c pairwise/FullPairwiseAlign.cpp -o pairwise/FullPairwiseAlign.o
pairwise/FullPairwiseAlign.cpp:7:14: fatal error: config.h: No such file or directory
    7 |     #include "config.h"
      |              ^~~~~~~~~~
compilation terminated.
make[2]: *** [/home/biocbuild/bbs-3.17-bioc/R/etc/Makeconf:198: pairwise/FullPairwiseAlign.o] Error 1
make[2]: Leaving directory '/home/biocbuild/bbs-3.17-bioc/meat/msa/src/ClustalW/src'
make[1]: *** [msaMakefile:8: clustalw] Error 1
make[1]: Leaving directory '/home/biocbuild/bbs-3.17-bioc/meat/msa/src/ClustalW'
make: *** [Makevars:28: build_clustalw] Error 2
ERROR: compilation failed for package ‘msa’
* removing ‘/home/biocbuild/bbs-3.17-bioc/R/library/msa’
```

We found that the:
- https://github.com/UBod/msa/tree/master/src/ClustalW
- https://github.com/UBod/msa/tree/master/src/ClustalOmega

The config.guess/config.sub is outdated, we need to update to latest, what we need to do is just:
```
cd src/ClustalW
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.sub -O ./config.sub
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.guess -O ./config.guess

cd src/ClustalOmega
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.sub -O ./config.sub
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.guess -O ./config.guess
```

See also: https://github.com/Yikun/BBS/issues/28

### PR DESCRIPTION
**Pull request by Yikun**
The config.guess/config.sub is outdate (see lastest [1][2]) so that it can be supported linux aarch64 well.

This patch update the config to latest:
```
cd src/ClustalW
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.sub -O ./config.sub
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.guess -O ./config.guess

cd src/ClustalOmega
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.sub -O ./config.sub
wget http://cvs.savannah.gnu.org/viewvc/\*checkout\*/config/config/config.guess -O ./config.guess
```

Closes: https://github.com/UBod/msa/issues/23

[1] http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
[2] http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

Signed-off-by: Yikun Jiang <yikunkero@gmail.com>

### CODE REVIEW

**Comment by Yikun** [comment]
I manually test on my local repo:

```
$ BiocManager::install("Yikun/msa")

installing to /home/biocbuild/bbs-3.17-bioc/R/library/00LOCK-msa/00new/msa/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (msa)
```

It works!

**Comment by Yikun** [comment]
@UBod Thanks for your help!

**Comment by Yikun** [comment]
https://code.bioconductor.org/browse/msa/master/

@UBod Could you please update the bioconductor repo with this improvement and a version bump? Thank you!

**Comment by UBod** [comment]
I wanted to, but I still get an error when pushing to the BioC repo. I will try to solve this problem in due course.

**Comment by Yikun** [comment]
I'm not sure it's pushing issue or some other issue you hitted, anyway I also do a double confirm build and check work:
- Build:
```
~/bbs-3.17-bioc/R/bin/R CMD build msa
* checking for file ‘msa/DESCRIPTION’ ... OK
* preparing ‘msa’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* installing the package to build vignettes
* creating vignettes ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘msa_1.31.3.tar.gz’
```

- Check

```
$ ~/bbs-3.17-bioc/R/bin/R CMD check msa_1.31.3.tar.gz
* using log directory ‘/home/biocbuild/yikun/msa.Rcheck’
* using R Under development (unstable) (2023-01-14 r83615)
* using platform: aarch64-unknown-linux-gnu (64-bit)
* R was compiled by
    gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
* running under: Ubuntu 22.04.1 LTS
* using session charset: UTF-8
* checking for file ‘msa/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘msa’ version ‘1.31.3’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* used C++ compiler: ‘g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
* used C compiler: ‘gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0’
* checking installed package size ... NOTE
  installed size is 26.9Mb
  sub-directories of 1Mb or more:
    libs  25.3Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking include directives in Makefiles ... OK
* checking compiled code ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘msa.Rnw’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
```

Please let me know if I can help more.

**Comment by UBod** [comment]
Excellent, thanks! It also worked nicely on my Ubuntu x86_64 system, so the update did not break anything.

**Comment by UBod** [comment]
I could push to the BioC devel repo now. The change is not yet visible on [https://code.bioconductor.org/browse/msa/master/](https://code.bioconductor.org/browse/msa/master/), but I hope it will soon become.

**Comment by Yikun** [comment]
@UBod Thanks! I can see it now.

**Pull request merged**
